# Hardware extras — GPU, CPU, firmware settings.
# This file supplements hardware-configuration.nix (auto-generated by
# nixos-generate-config) with additional hardware tweaks.
#
# On a fresh install, preserve this file and regenerate only
# hardware-configuration.nix:
#
#   sudo nixos-generate-config --root /mnt
#   sudo cp /mnt/etc/nixos/hardware-configuration.nix \
#           /mnt/etc/nixos/hardware-configuration.nix

{
  config,
  lib,
  pkgs,
  ...
}:

{
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {
    modesetting.enable = true;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # ── Swap file (16 GB) — prevents OOM freezes ──
  swapDevices = [
    {
      device = "/swapfile";
      size = 16384;
    }
  ];

  hardware.cpu.amd.updateMicrocode = true;
  powerManagement.cpuFreqGovernor = "performance";

  # ── CUDA toolkit for GPU-accelerated apps (QMD, llama.cpp, etc.) ──
  environment.systemPackages = with pkgs; [
    cudaPackages.cudatoolkit
  ];
}
