# Hardware extras — GPU, CPU, firmware settings.
# This file supplements hardware-configuration.nix (auto-generated by
# nixos-generate-config) with additional hardware tweaks.
#
# On a fresh install, preserve this file and regenerate only
# hardware-configuration.nix:
#
#   sudo nixos-generate-config --root /mnt
#   sudo cp /mnt/etc/nixos/hardware-configuration.nix \
#           /mnt/etc/nixos/hardware-configuration.nix

{
  config,
  lib,
  pkgs,
  ...
}:

{
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {
    modesetting.enable = true;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  hardware.cpu.amd.updateMicrocode = true;
  powerManagement.cpuFreqGovernor = "performance";
}
